name: build sb3

on: push

jobs:
    tools:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: checkout elvm
              uses: actions/checkout@v4
              with:
                  repository: shinh/elvm
                  path: elvm
            - name: build elc + 8cc
              run: cd elvm && make out/8cc out/elc && cp ./out/* .. && cp -r ./tools/ .. && cd ..
            - name: upload everythinh
              uses: actions/upload-artifact@v4
              with:
                  name: cwd
                  path: ./
    build:
        runs-on: ubuntu-latest
        needs: elc
        steps:
            - uses: actions/download-artifact@v4 # this also checks out our whole repo cuz we uploaded everything on . that we had
              with:
                  name: cwd
            - name: compileth
              run: |
                  ls -la
                  chmod +x elc tools/gen_scratch_sb3.sh
                  ./8cc patata.c -S -I. -Ilibc -o patata.eir
                  ./elc -scratch3 patata.eir > patata.json
                  ./tools/gen_scratch_sb3.sh patata.json -name out
            - name: upload artifact to internet archive ig
              uses: actions/upload-artifact@v4
              with:
                  name: output
                  path: ./